### ISSUE TITLE
[2021.12.21 ~ 2021.12.30] 진행해야 할 테스크 정리

### ISSUE THREAD

**Issue by sirldev** [KMU-WINK/instagram-server#10]
# [2021.12.21 ~ 2021.12.30] 진행해야 할 테스크 정리

> 해당 문서는 12월 30일까지 진행할 테스크를 정리하기 위한 문서입니다. 자신이 할 업무를 숙지해주신 뒤, Issue에 등록 후 PR을 보내주시면 검토 후 Merge 하도록 하겠습니다.

## 참여 개발 인원
- 김찬호 
- 송민준 
- 임성원
- 차영호 
- 하준혁

## 개발 시 유의사항
유저 관련 처리는 JWT 를 베이스로 처리할 예정. ( 구현은 완료되었으나 하단 개선사항과 같은 추가적인 구현이 존재합니다. )
REST API 를 구현하는 것을 목표로 합니다. 

[이 글](https://sanghaklee.tistory.com/57)을 읽어보신 후 RESTful 한 API에 대하여 생각해보시고 구현해주시면 좋을 것 같습니다. 🙏

특히 4,5,6 문단은 필수적으로 생각해주시길 바라겠습니다.

제가 라이브러리까지 언급한 경우, 구글에 굉장히 많은 레퍼런스가 존재하기 때문에 왜 구현하는 지도 알아보시면 좋을 것 같습니다.

### 개선 사항
- 현재 구현 된 API RESTAPI + Json 형식으로 변경 ( [이 글](https://kukekyakya.tistory.com/41) 확인 후 문서화도 부탁드립니다. )
  - [ ] 유저
  - [ ] #11
  - [ ] 댓글
  - [ ] 이미지 업로드
- 기타 개선 사항
  - [ ] 유저 비밀번호 저장 및 로그인 시 bcrypt 라이브러리를 활용하여 안전하게 저장하기

### 신규 개발
- 새로운 모델 만들기
  - [ ] 카테고리 모델 생성

**Comment by sirldev** [comment]
일단 제가 생각난대로 적어본 부분들입니다.

개발 중 궁금한 부분이 있으시다면 백엔드 단톡방에 질문 부탁드리겠습니다.

**Comment by sirldev** [comment]
https://www.notion.so/907a24ea6ee7480f8e004e5fc8d8dd49

Fork 후 작업 방법 링크입니다.

**Comment by ChanHHOO** [comment]
카테고리 모델링 맡겠습니다. 남은 테스크는   user, bcrypt / comment, iamge /  article 이렇게 세 파트로 나눠 담당하시면 될 것 같습니다!

**Comment by minjun7410** [comment]
그럼 저는 user를 맡겠습니다. 코드를 이해할 때까지 백엔드를 공부한 다음 개발 시작하도록하겠습니다.

**Comment by ChanHHOO** [comment]
user와 bcrypt 까지 맡으셔야 합니다 !

**Comment by minjun7410** [comment]
아 슬래시 구분을 잘못했네요! user랑 bcypt를 맡을게요

**Comment by youngh0** [comment]
comment, image 해보겠습니다!

**Comment by KMUsungwon** [comment]
article 파트 맡아서 하겠습니다
