### ISSUE TITLE
게시글 관련 모델링

### ISSUE THREAD

**Issue by sirldev** [KMU-WINK/instagram-server#4]

**Comment by sirldev** [comment]
**회의 후 정해진 게시글 및 댓글 모델링 입니다.**

이후 변경될 수 있습니다.

![image](https://user-images.githubusercontent.com/59739164/142423178-b9084784-d28c-4d06-ba73-a8013cfdc9c6.png)

**Comment by sirldev** [comment]
**논의가 필요한 부분** 
- 스토리, 게시글 에서 다른 유저 태깅

- 드래그 앤 드롭 했을때 게시글의 위치가 대치되는건지 아니면 그쪽부터 밀려나는건지

**Comment by ChanHHOO** [comment]
드래그 앤 드롭 기능 구현하려면 article에 순서정보가 담길 컬럼이 있어야 하지 않을까요 ?

**Comment by ChanHHOO** [comment]
aticle 테이블에 user column과 user table이 중복이어서 오류가 납니다. article table에서 user컬럼을 owner로 수정 요청합니다.
